@extends('layouts.dashboard')

@section('content')
    <section class="p-5 lg:p-10">
        <div class="flex flex-wrap items-end justify-between gap-4">
            <div><p class="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Keuangan sekolah</p><h1 class="mt-2 font-display text-4xl text-emerald-950">Pembayaran siswa</h1><p class="mt-2 text-sm text-slate-500">Catat pembayaran bulanan dan pantau statusnya.</p></div>
        </div>
        <form method="post" action="{{ route('dashboard.payments.store') }}" class="dashboard-card mt-8 grid gap-3 rounded-2xl bg-white p-5 sm:grid-cols-2 lg:grid-cols-5">
            @csrf
            <select name="student_id" required class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Pilih siswa</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->nama_lengkap }} · {{ strtoupper($student->unit) }}</option>@endforeach</select>
            <select name="bulan" required class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Bulan</option>@for($month = 1; $month <= 12; $month++)<option value="{{ $month }}">Bulan {{ $month }}</option>@endfor</select>
            <input name="tahun" type="number" value="{{ now()->year }}" min="2020" max="2100" required class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Tahun">
            <input name="nominal" type="number" min="0" required class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm" placeholder="Nominal">
            <div class="flex gap-2"><select name="status_bayar" required class="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="belum_lunas">Belum lunas</option><option value="lunas">Lunas</option></select><button class="rounded-xl bg-emerald-800 px-4 py-2 text-sm font-bold text-white" title="Simpan pembayaran" aria-label="Simpan pembayaran"><i class="fa-solid fa-plus"></i></button></div>
        </form>
        <form method="get" class="dashboard-card mt-5 flex flex-wrap gap-2 rounded-2xl bg-white p-4"><input name="q" value="{{ request('q') }}" placeholder="Cari nama atau NISN" class="min-w-[220px] flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><select name="unit" class="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">Semua unit</option><option value="mi" @selected(request('unit') === 'mi')>MI</option><option value="mts" @selected(request('unit') === 'mts')>MTs</option></select><input name="tahun" value="{{ request('tahun', now()->year) }}" type="number" class="w-28 rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><button class="rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">Filter</button></form>
        <div class="mt-5 overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="w-full min-w-[720px] text-left text-sm"><thead class="border-b border-slate-100 text-xs uppercase tracking-wider text-slate-400"><tr><th class="px-5 py-4">Siswa</th><th class="px-5 py-4">Periode</th><th class="px-5 py-4">Nominal</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($payments as $payment)<tr><td class="px-5 py-4 font-semibold text-emerald-950">{{ $payment->student->nama_lengkap }}<small class="block font-normal text-slate-400">{{ strtoupper($payment->student->unit) }} · {{ $payment->student->nisn }}</small></td><td class="px-5 py-4 text-slate-500">{{ $payment->bulan }}/{{ $payment->tahun }}</td><td class="px-5 py-4 text-slate-600">Rp {{ number_format($payment->nominal, 0, ',', '.') }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $payment->status_bayar === 'lunas' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800' }}">{{ str_replace('_', ' ', ucfirst($payment->status_bayar)) }}</span></td><td class="px-5 py-4"><form method="post" action="{{ route('dashboard.payments.update', $payment) }}">@csrf @method('put')<input type="hidden" name="status_bayar" value="{{ $payment->status_bayar === 'lunas' ? 'belum_lunas' : 'lunas' }}"><button class="text-xs font-bold text-emerald-700">Tandai {{ $payment->status_bayar === 'lunas' ? 'belum lunas' : 'lunas' }}</button></form></td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-slate-500">Belum ada data pembayaran.</td></tr>@endforelse</tbody></table></div>
        <div class="mt-5">{{ $payments->links() }}</div>
    </section>
@endsection