@extends('layouts.dashboard')

@section('content')
<section class="p-5 lg:p-10">
    <div class="flex flex-wrap items-end justify-between gap-4">
        <div>
            <p class="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Konten publik</p>
            <h1 class="mt-2 font-display text-4xl text-emerald-950">Pengaturan landing page</h1>
            <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Kelola teks utama, gambar hero, tombol pendaftaran, dan informasi kontak tanpa menyentuh kode.</p>
        </div>
        <a href="{{ route('home') }}" target="_blank" rel="noopener" class="rounded-xl border border-emerald-900/10 bg-white px-4 py-2.5 text-sm font-bold text-emerald-800"><i class="fa-solid fa-arrow-up-right-from-square mr-2"></i>Lihat landing page</a>
    </div>

    <form method="post" action="{{ route('dashboard.site-settings.update') }}" class="mt-8 grid gap-6 xl:grid-cols-[1.1fr_.9fr]">
        @csrf
        @method('put')
        <div class="dashboard-card rounded-3xl bg-white p-6 lg:p-8">
            <div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-800"><i class="fa-solid fa-wand-magic-sparkles"></i></span><div><h2 class="font-bold text-emerald-950">Hero utama</h2><p class="text-xs text-slate-500">Bagian pertama yang dilihat pengunjung.</p></div></div>
            <div class="mt-6 space-y-5">
                <label class="block"><span class="text-sm font-semibold text-slate-700">Label kecil</span><input name="hero_badge" value="{{ old('hero_badge', $settings['hero_badge']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label>
                <label class="block"><span class="text-sm font-semibold text-slate-700">Judul hero</span><input name="hero_title" value="{{ old('hero_title', $settings['hero_title']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label>
                <label class="block"><span class="text-sm font-semibold text-slate-700">Deskripsi</span><textarea name="hero_description" rows="4" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">{{ old('hero_description', $settings['hero_description']) }}</textarea></label>
                <label class="block"><span class="text-sm font-semibold text-slate-700">URL gambar hero</span><input type="url" name="hero_image" value="{{ old('hero_image', $settings['hero_image']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label>
                <div class="grid gap-4 md:grid-cols-2"><label class="block"><span class="text-sm font-semibold text-slate-700">Teks tombol utama</span><input name="hero_primary_label" value="{{ old('hero_primary_label', $settings['hero_primary_label']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label><label class="block"><span class="text-sm font-semibold text-slate-700">Link tombol utama</span><input name="hero_primary_url" value="{{ old('hero_primary_url', $settings['hero_primary_url']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label></div>
            </div>
        </div>
        <div class="space-y-6">
            <div class="dashboard-card rounded-3xl bg-white p-6 lg:p-8"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-700"><i class="fa-solid fa-address-book"></i></span><div><h2 class="font-bold text-emerald-950">Kontak yayasan</h2><p class="text-xs text-slate-500">Tampil di footer dan informasi publik.</p></div></div><div class="mt-6 space-y-5"><label class="block"><span class="text-sm font-semibold text-slate-700">Nomor telepon</span><input name="contact_phone" value="{{ old('contact_phone', $settings['contact_phone']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label><label class="block"><span class="text-sm font-semibold text-slate-700">Alamat</span><textarea name="contact_address" rows="3" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">{{ old('contact_address', $settings['contact_address']) }}</textarea></label></div></div>
            <div class="dashboard-card overflow-hidden rounded-3xl bg-emerald-900 p-6 text-white"><p class="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Pratinjau cepat</p><h2 class="mt-3 font-display text-3xl">{{ $settings['hero_title'] }}</h2><p class="mt-3 text-sm leading-6 text-emerald-50/70">{{ $settings['hero_description'] }}</p><button class="mt-6 inline-flex items-center gap-2 rounded-xl bg-amber-300 px-5 py-3 text-sm font-bold text-emerald-950"><i class="fa-solid fa-floppy-disk"></i>Simpan semua perubahan</button></div>
        </div>
        <div class="dashboard-card rounded-3xl bg-white p-6 lg:p-8 xl:col-span-2"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-100 text-emerald-800"><i class="fa-solid fa-newspaper"></i></span><div><h2 class="font-bold text-emerald-950">Berita & pengumuman</h2><p class="text-xs text-slate-500">Tiga berita ini tampil di landing page.</p></div></div><div class="mt-6 grid gap-5 lg:grid-cols-3">@foreach($settings['news'] as $index => $news)<div class="rounded-2xl border border-slate-200 bg-slate-50 p-4"><p class="mb-4 text-xs font-bold text-emerald-700">Berita {{ $index + 1 }}</p><div class="space-y-3"><input name="news[{{ $index }}][tag]" value="{{ old('news.'.$index.'.tag', $news['tag']) }}" placeholder="Kategori" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><input name="news[{{ $index }}][date]" value="{{ old('news.'.$index.'.date', $news['date']) }}" placeholder="Tanggal" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><input name="news[{{ $index }}][title]" value="{{ old('news.'.$index.'.title', $news['title']) }}" placeholder="Judul berita" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><textarea name="news[{{ $index }}][excerpt]" rows="3" placeholder="Ringkasan" class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm">{{ old('news.'.$index.'.excerpt', $news['excerpt']) }}</textarea></div></div>@endforeach</div></div>
        <div class="dashboard-card rounded-3xl bg-white p-6 lg:p-8 xl:col-span-2"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-amber-100 text-amber-700"><i class="fa-solid fa-pen-to-square"></i></span><div><h2 class="font-bold text-emerald-950">PPDB Online</h2><p class="text-xs text-slate-500">Kelola informasi penerimaan siswa baru.</p></div></div><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="block"><span class="text-sm font-semibold text-slate-700">Judul PPDB</span><input name="ppdb_title" value="{{ old('ppdb_title', $settings['ppdb_title']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label><label class="block"><span class="text-sm font-semibold text-slate-700">Status pendaftaran</span><input name="ppdb_status" value="{{ old('ppdb_status', $settings['ppdb_status']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label><label class="block md:col-span-2"><span class="text-sm font-semibold text-slate-700">Deskripsi PPDB</span><textarea name="ppdb_description" rows="3" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">{{ old('ppdb_description', $settings['ppdb_description']) }}</textarea></label><label class="block md:col-span-2"><span class="text-sm font-semibold text-slate-700">Teks informasi CTA</span><input name="ppdb_cta" value="{{ old('ppdb_cta', $settings['ppdb_cta']) }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3"></label></div></div>
    </form>
</section>
@endsection